name: Build & Deploy to P.sh Dev
on: push

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      bundles: ${{ steps.set-bundles.outputs.bundles }}
    steps:

      - id: set-bundles
        run: echo "::set-output name=bundles::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
        
      - name: Generate P.sh project name
        env:
          PR: 4
        id: projectGen
        run: |
          echo "::set-output name=name::[PR-${PR}] ezsystems/ezplatform-admin-ui"

      - name: Output project name
        run: |
          echo "Project name is \"${{ steps.projectGen.outputs.name }}\""

  # uses dependency tree to run package installation
  patch:
    runs-on: ubuntu-latest
    needs: pre
    strategy:
      matrix: ${{fromJSON(needs.pre.outputs.bundles)}}
    steps:
      - run: |
          echo ${{ matrix.project }}
          echo ${{ matrix.config }}

